# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('bundle-protocol-simple', ['bundle-protocol', 'point-to-point'])
    obj.source = 'bundle-protocol-simple.cc'
    
    obj = bld.create_ns3_program('bundle-protocol-ltp-simple', ['ltp-protocol', 'bundle-protocol', 'point-to-point'])
    obj.source = 'bundle-protocol-ltp-simple.cc'

    obj = bld.create_ns3_program('bundle-protocol-nocla', ['bundle-protocol', 'point-to-point'])
    obj.source = 'bundle-protocol-nocla.cc'
        
    obj = bld.create_ns3_program('bundle-protocol-multihop-tcp', ['bundle-protocol', 'point-to-point'])
    obj.source = 'bundle-protocol-multihop-tcp.cc'
    
    obj = bld.create_ns3_program('bundle-protocol-multihop-ltp', ['ltp-protocol', 'bundle-protocol', 'point-to-point'])
    obj.source = 'bundle-protocol-multihop-ltp.cc'
    
    obj = bld.create_ns3_program('bundle-protocol-multihop-linkstatuschange-tcp', ['bundle-protocol', 'point-to-point'])
    obj.source = 'bundle-protocol-multihop-linkstatuschange-tcp.cc'
